In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\DELL\Downloads\sales_raw_data.csv")
df.head()

   order_id  product     category region    sales  profit        date
0         1   Laptop    Computers   East  40000.0  5000.0   10/2/2025
1         2    Chair    Furniture   West   1500.0   200.0  15/02/2025
2         3     Sofa    Furniture    NaN   4000.0   500.0  20/02/2025
3         4  Desktop    Computers  North      NaN  2000.0  25/02/2025
4         5   Mobile  Electronics  South  35000.0     NaN  26/02/2025

In [3]:
df=pd.read_csv(r"C:\Users\DELL\Downloads\sales_raw_data.csv")
#df.head()
df.info()
#df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  7 non-null      int64
 1   product   7 non-null      object
 2   category  7 non-null      object
 3   region    6 non-null      object
 4   sales     6 non-null      float64
 5   profit    6 non-null      float64
 6   date      7 non-null      object
dtypes: float64(2), int64(1), object(4)
memory usage: 524.0+ bytes

In [4]:
df=pd.read_csv(r"C:\Users\DELL\Downloads\sales_raw_data.csv")
#df.head()
#df.info()
df.isnull().sum()

order_id    0
product     0
category    0
region      1
sales       1
profit      1
date        0
dtype: int64

In [5]:
### CATEGORICAL MISSING VALUES
df=pd.read_csv(r"C:\Users\DELL\Downloads\sales_raw_data.csv")
df['region'].fillna(df['region'].mode()[0])
print(df)

   order_id  product     category region    sales  profit        date
0         1   Laptop    Computers   East  40000.0  5000.0   10/2/2025
1         2    Chair    Furniture   West   1500.0   200.0  15/02/2025
2         3     Sofa    Furniture    NaN   4000.0   500.0  20/02/2025
3         4  Desktop    Computers  North      NaN  2000.0  25/02/2025
4         5   Mobile  Electronics  South  35000.0     NaN  26/02/2025
5         1   Laptop    Computers   East  40000.0  5000.0   10/2/2025
6         2    Chair    Furniture   West   1500.0   200.0  15/02/2025

In [6]:
df['region']=df['region'].fillna(df['region'].mode()[0])
print(df)

   order_id  product     category region    sales  profit        date
0         1   Laptop    Computers   East  40000.0  5000.0   10/2/2025
1         2    Chair    Furniture   West   1500.0   200.0  15/02/2025
2         3     Sofa    Furniture   East   4000.0   500.0  20/02/2025
3         4  Desktop    Computers  North      NaN  2000.0  25/02/2025
4         5   Mobile  Electronics  South  35000.0     NaN  26/02/2025
5         1   Laptop    Computers   East  40000.0  5000.0   10/2/2025
6         2    Chair    Furniture   West   1500.0   200.0  15/02/2025

In [14]:
### Handling missing  Numerical& Outliers
import pandas as pd
df=pd.read_csv(r"C:\Users\DELL\Downloads\sales_raw_data.csv")
df['sales']=df['sales'].fillna(df['sales'].mean())
df['region']=df['region'].fillna(df['region'].mode()[0])
print(df)

   order_id  product     category region         sales  profit        date
0         1   Laptop    Computers   East  40000.000000  5000.0   10/2/2025
1         2    Chair    Furniture   West   1500.000000   200.0  15/02/2025
2         3     Sofa    Furniture   East   4000.000000   500.0  20/02/2025
3         4  Desktop    Computers  North  20333.333333  2000.0  25/02/2025
4         5   Mobile  Electronics  South  35000.000000     NaN  26/02/2025
5         1   Laptop    Computers   East  40000.000000  5000.0   10/2/2025
6         2    Chair    Furniture   West   1500.000000   200.0  15/02/2025

In [15]:
df=pd.read_csv(r"C:\Users\DELL\Downloads\sales_raw_data.csv")
df.duplicated().sum()
#df.drop_duplicates(inplace=True)

np.int64(2)

In [16]:
df=pd.read_csv(r"C:\Users\DELL\Downloads\sales_raw_data.csv")
df.duplicated().sum()

np.int64(2)

In [17]:
df=pd.read_csv(r"C:\Users\DELL\Downloads\sales_raw_data.csv")
df.duplicated().sum()
df.drop_duplicates(inplace=True)
df

   order_id  product     category region    sales  profit        date
0         1   Laptop    Computers   East  40000.0  5000.0   10/2/2025
1         2    Chair    Furniture   West   1500.0   200.0  15/02/2025
2         3     Sofa    Furniture    NaN   4000.0   500.0  20/02/2025
3         4  Desktop    Computers  North      NaN  2000.0  25/02/2025
4         5   Mobile  Electronics  South  35000.0     NaN  26/02/2025

In [18]:
###
###STEP 1:LOAD &CLEAN DATA
import pandas as pd
df=pd.read_csv(r"C:\Users\DELL\Downloads\Retail_sales.csv")
df.drop_duplicates()
df.fillna(0)
df["Oder_Date"]=pd.to_datetime(df["Oder_Date"])
#df["Year"]=df["Oder_Date"].dt.year
#df["Month"]=df["Oder_Date"].dt.month
#df["Day"]=df["Oder_Date"].dt.day
#df["Weekday"]=df["Oder_Date"].dt.weekday
df

,Oder_Id,Oder_Date,Region,Product_Category,Sales_Amount,Quantity,Profit
0,1001.0,2024-01-01,North,Electronics,25000.0,5.0,4000.0
1,1002.0,2024-02-01,South,Furniture,18000.0,3.0,3000.0
2,1003.0,2024-03-01,East,Clothing,12000.0,10.0,2500.0
3,1004.0,2024-04-01,West,Electronics,30000.0,6.0,6000.0
4,1005.0,2024-05-01,North,Clothing,1500.0,8.0,2800.0
5,1006.0,2024-06-01,South,Furniture,20000.0,4.0,3500.0
6,1007.0,2024-07-01,East,Electronics,28000.0,7.0,5200.0
7,1008.0,2024-08-01,West,Clothing,11000.0,9.0,2000.0
8,1009.0,2024-09-01,North,Furniture,22000.0,5.0,4200.0
9,1010.0,2024-10-01,South,Electronics,26000.0,6.0,48000.0
10,NaN,NaT,NaN,NaN,NaN,NaN,NaN

In [19]:
###STEP:2 FEATURE ENGINEERING:DATA EXTRACTION
df["Year"]=df["Oder_Date"].dt.year
df["Month"]=df["Oder_Date"].dt.month
df["Day"]=df["Oder_Date"].dt.day
df["Weekday"]=df["Oder_Date"].dt.weekday
df

,Oder_Id,Oder_Date,Region,Product_Category,Sales_Amount,Quantity,Profit,Year,Month,Day,Weekday
0,1001.0,2024-01-01,North,Electronics,25000.0,5.0,4000.0,2024.0,1.0,1.0,0.0
1,1002.0,2024-02-01,South,Furniture,18000.0,3.0,3000.0,2024.0,2.0,1.0,3.0
2,1003.0,2024-03-01,East,Clothing,12000.0,10.0,2500.0,2024.0,3.0,1.0,4.0
3,1004.0,2024-04-01,West,Electronics,30000.0,6.0,6000.0,2024.0,4.0,1.0,0.0
4,1005.0,2024-05-01,North,Clothing,1500.0,8.0,2800.0,2024.0,5.0,1.0,2.0
5,1006.0,2024-06-01,South,Furniture,20000.0,4.0,3500.0,2024.0,6.0,1.0,5.0
6,1007.0,2024-07-01,East,Electronics,28000.0,7.0,5200.0,2024.0,7.0,1.0,0.0
7,1008.0,2024-08-01,West,Clothing,11000.0,9.0,2000.0,2024.0,8.0,1.0,3.0
8,1009.0,2024-09-01,North,Furniture,22000.0,5.0,4200.0,2024.0,9.0,1.0,6.0
9,1010.0,2024-10-01,South,Electronics,26000.0,6.0,48000.0,2024.0,10.0,1.0,1.0
10,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
#STEP3: CATEGORICAL ENCODING
#ENCODE CATEGORY&REGION
df=pd.read_csv(r"C:\Users\DELL\Downloads\Retail_sales.csv")
df_encoded=pd.get_dummies(df,columns=["Product_Category","Region"])#,drop_first=True#)
df_encoded

,Oder_Id,Oder_Date,Sales_Amount,Quantity,Profit,Product_Category_Clothing,Product_Category_Electronics,Product_Category_Furniture,Region_East,Region_North,Region_South,Region_West
0,1001.0,1/1/2024,25000.0,5.0,4000.0,False,True,False,False,True,False,False
1,1002.0,2/1/2024,18000.0,3.0,3000.0,False,False,True,False,False,True,False
2,1003.0,3/1/2024,12000.0,10.0,2500.0,True,False,False,True,False,False,False
3,1004.0,4/1/2024,30000.0,6.0,6000.0,False,True,False,False,False,False,True
4,1005.0,5/1/2024,1500.0,8.0,2800.0,True,False,False,False,True,False,False
5,1006.0,6/1/2024,20000.0,4.0,3500.0,False,False,True,False,False,True,False
6,1007.0,7/1/2024,28000.0,7.0,5200.0,False,True,False,True,False,False,False
7,1008.0,8/1/2024,11000.0,9.0,2000.0,True,False,False,False,False,False,True
8,1009.0,9/1/2024,22000.0,5.0,4200.0,False,False,True,False,True,False,False
9,1010.0,10/1/2024,26000.0,6.0,48000.0,False,True,False,False,False,True,False
10,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False,False,False

In [21]:
df=pd.read_csv(r"C:\Users\DELL\Downloads\Retail_sales.csv")
df_encoded=pd.get_dummies(df,columns=["Product_Category","Region"],drop_first=True)
df_encoded

,Oder_Id,Oder_Date,Sales_Amount,Quantity,Profit,Product_Category_Electronics,Product_Category_Furniture,Region_North,Region_South,Region_West
0,1001.0,1/1/2024,25000.0,5.0,4000.0,True,False,True,False,False
1,1002.0,2/1/2024,18000.0,3.0,3000.0,False,True,False,True,False
2,1003.0,3/1/2024,12000.0,10.0,2500.0,False,False,False,False,False
3,1004.0,4/1/2024,30000.0,6.0,6000.0,True,False,False,False,True
4,1005.0,5/1/2024,1500.0,8.0,2800.0,False,False,True,False,False
5,1006.0,6/1/2024,20000.0,4.0,3500.0,False,True,False,True,False
6,1007.0,7/1/2024,28000.0,7.0,5200.0,True,False,False,False,False
7,1008.0,8/1/2024,11000.0,9.0,2000.0,False,False,False,False,True
8,1009.0,9/1/2024,22000.0,5.0,4200.0,False,True,True,False,False
9,1010.0,10/1/2024,26000.0,6.0,48000.0,True,False,False,True,False
10,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False

In [22]:
##STEP:4 BUSINESS FEATURE CREATION(REAL-WORLD)
### 1.PROFIT MARGIN

df_encoded["Profit_Margin"]=df_encoded["Profit"] / df_encoded["Sales_Amount"]
df_encoded["Profit_Margin"].fillna(0)
df_encoded

,Oder_Id,Oder_Date,Sales_Amount,Quantity,Profit,Product_Category_Electronics,Product_Category_Furniture,Region_North,Region_South,Region_West,Profit_Margin
0,1001.0,1/1/2024,25000.0,5.0,4000.0,True,False,True,False,False,0.160000
1,1002.0,2/1/2024,18000.0,3.0,3000.0,False,True,False,True,False,0.166667
2,1003.0,3/1/2024,12000.0,10.0,2500.0,False,False,False,False,False,0.208333
3,1004.0,4/1/2024,30000.0,6.0,6000.0,True,False,False,False,True,0.200000
4,1005.0,5/1/2024,1500.0,8.0,2800.0,False,False,True,False,False,1.866667
5,1006.0,6/1/2024,20000.0,4.0,3500.0,False,True,False,True,False,0.175000
6,1007.0,7/1/2024,28000.0,7.0,5200.0,True,False,False,False,False,0.185714
7,1008.0,8/1/2024,11000.0,9.0,2000.0,False,False,False,False,True,0.181818
8,1009.0,9/1/2024,22000.0,5.0,4200.0,False,True,True,False,False,0.190909
9,1010.0,10/1/2024,26000.0,6.0,48000.0,True,False,False,True,False,1.846154
10,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False,NaN

In [23]:
##STEP:4 BUSINESS FEATURE CREATION(REAL-WORLD)
####2.HIFH-PROFIT LABEL(CLASSIFICATION TARGET)
df_encoded["High_Profit"]=df_encoded["Profit"].apply(lambda x:1 if x>df_encoded["Profit"].median() else 0)
df_encoded

,Oder_Id,Oder_Date,Sales_Amount,Quantity,Profit,Product_Category_Electronics,Product_Category_Furniture,Region_North,Region_South,Region_West,Profit_Margin,High_Profit
0,1001.0,1/1/2024,25000.0,5.0,4000.0,True,False,True,False,False,0.160000,1
1,1002.0,2/1/2024,18000.0,3.0,3000.0,False,True,False,True,False,0.166667,0
2,1003.0,3/1/2024,12000.0,10.0,2500.0,False,False,False,False,False,0.208333,0
3,1004.0,4/1/2024,30000.0,6.0,6000.0,True,False,False,False,True,0.200000,1
4,1005.0,5/1/2024,1500.0,8.0,2800.0,False,False,True,False,False,1.866667,0
5,1006.0,6/1/2024,20000.0,4.0,3500.0,False,True,False,True,False,0.175000,0
6,1007.0,7/1/2024,28000.0,7.0,5200.0,True,False,False,False,False,0.185714,1
7,1008.0,8/1/2024,11000.0,9.0,2000.0,False,False,False,False,True,0.181818,0
8,1009.0,9/1/2024,22000.0,5.0,4200.0,False,True,True,False,False,0.190909,1
9,1010.0,10/1/2024,26000.0,6.0,48000.0,True,False,False,True,False,1.846154,1
10,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False,NaN,0

In [24]:
###### STEP:5 FEATURE SCALING(ML ESSENTIAL)

from sklearn.preprocessing import StandardScaler
#df=pd.read_csv(r"C:\Users\DELL\Downloads\Retail_sales.csv")
scaler=StandardScaler()
num_cols=["Quantity","Sales_Amount","Profit","Profit_Margin"]
df_encoded[num_cols]=scaler.fit_transform(df_encoded[num_cols])
df_encoded

,Oder_Id,Oder_Date,Sales_Amount,Quantity,Profit,Product_Category_Electronics,Product_Category_Furniture,Region_North,Region_South,Region_West,Profit_Margin,High_Profit
0,1001.0,1/1/2024,0.667705,-0.619048,-0.308748,True,False,True,False,False,-0.535078,1
1,1002.0,2/1/2024,-0.159540,-1.571429,-0.383687,False,True,False,True,False,-0.525118,0
2,1003.0,3/1/2024,-0.868607,1.761905,-0.421157,False,False,False,False,False,-0.462863,0
3,1004.0,4/1/2024,1.258594,-0.142857,-0.158871,True,False,False,False,True,-0.475314,1
4,1005.0,5/1/2024,-2.109474,0.809524,-0.398675,False,False,True,False,False,2.014862,0
5,1006.0,6/1/2024,0.076816,-1.095238,-0.346218,False,True,False,True,False,-0.512667,0
6,1007.0,7/1/2024,1.022238,0.333333,-0.218822,True,False,False,False,False,-0.496659,1
7,1008.0,8/1/2024,-0.986785,1.285714,-0.458626,False,False,False,False,True,-0.502480,0
8,1009.0,9/1/2024,0.313171,-0.619048,-0.293761,False,True,True,False,False,-0.488897,1
9,1010.0,10/1/2024,0.785882,-0.142857,2.988565,True,False,False,True,False,1.984214,1
10,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False,NaN,0

In [25]:
###### STEP 6:FEATURE & TARGRT SELECTION
### REGRESSION
X=df_encoded.drop(["Sales_Amount","Oder_Date","Oder_Id"],axis=1)
Y=df_encoded["Sales_Amount"]
df_encoded

,Oder_Id,Oder_Date,Sales_Amount,Quantity,Profit,Product_Category_Electronics,Product_Category_Furniture,Region_North,Region_South,Region_West,Profit_Margin,High_Profit
0,1001.0,1/1/2024,0.667705,-0.619048,-0.308748,True,False,True,False,False,-0.535078,1
1,1002.0,2/1/2024,-0.159540,-1.571429,-0.383687,False,True,False,True,False,-0.525118,0
2,1003.0,3/1/2024,-0.868607,1.761905,-0.421157,False,False,False,False,False,-0.462863,0
3,1004.0,4/1/2024,1.258594,-0.142857,-0.158871,True,False,False,False,True,-0.475314,1
4,1005.0,5/1/2024,-2.109474,0.809524,-0.398675,False,False,True,False,False,2.014862,0
5,1006.0,6/1/2024,0.076816,-1.095238,-0.346218,False,True,False,True,False,-0.512667,0
6,1007.0,7/1/2024,1.022238,0.333333,-0.218822,True,False,False,False,False,-0.496659,1
7,1008.0,8/1/2024,-0.986785,1.285714,-0.458626,False,False,False,False,True,-0.502480,0
8,1009.0,9/1/2024,0.313171,-0.619048,-0.293761,False,True,True,False,False,-0.488897,1
9,1010.0,10/1/2024,0.785882,-0.142857,2.988565,True,False,False,True,False,1.984214,1
10,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False,NaN,0

In [26]:
##### CLASSIFICATION
X=df_encoded.drop(["High_Profit","Oder_Date","Oder_Id"],axis=1)
Y=df_encoded["High_Profit"]
df_encoded

,Oder_Id,Oder_Date,Sales_Amount,Quantity,Profit,Product_Category_Electronics,Product_Category_Furniture,Region_North,Region_South,Region_West,Profit_Margin,High_Profit
0,1001.0,1/1/2024,0.667705,-0.619048,-0.308748,True,False,True,False,False,-0.535078,1
1,1002.0,2/1/2024,-0.159540,-1.571429,-0.383687,False,True,False,True,False,-0.525118,0
2,1003.0,3/1/2024,-0.868607,1.761905,-0.421157,False,False,False,False,False,-0.462863,0
3,1004.0,4/1/2024,1.258594,-0.142857,-0.158871,True,False,False,False,True,-0.475314,1
4,1005.0,5/1/2024,-2.109474,0.809524,-0.398675,False,False,True,False,False,2.014862,0
5,1006.0,6/1/2024,0.076816,-1.095238,-0.346218,False,True,False,True,False,-0.512667,0
6,1007.0,7/1/2024,1.022238,0.333333,-0.218822,True,False,False,False,False,-0.496659,1
7,1008.0,8/1/2024,-0.986785,1.285714,-0.458626,False,False,False,False,True,-0.502480,0
8,1009.0,9/1/2024,0.313171,-0.619048,-0.293761,False,True,True,False,False,-0.488897,1
9,1010.0,10/1/2024,0.785882,-0.142857,2.988565,True,False,False,True,False,1.984214,1
10,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False,NaN,0

In [27]:
##STEP 7:EXPORT ML-READY DATASET
df_encoded.to_csv("Retail_sales.csv",index=False)